import praw
import json
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class RedditPoster:
    def __init__(self, config_path="config.json"):
        """Initialize the Reddit poster with credentials from config file"""
        # Load credentials from environment variables
        client_id = os.getenv("REDDIT_CLIENT_ID")
        client_secret = os.getenv("REDDIT_CLIENT_SECRET")
        username = os.getenv("REDDIT_USERNAME")
        password = os.getenv("REDDIT_PASSWORD")
        user_agent = os.getenv("REDDIT_USER_AGENT", "RedditAI/1.0 by u/your_username")
        
        # Initialize PRAW instance
        self.reddit = praw.Reddit(
            client_id=client_id,
            client_secret=client_secret,
            username=username,
            password=password,
            user_agent=user_agent
        )
        
        # Load additional config from file if needed
        try:
            with open(config_path, 'r') as f:
                self.config = json.load(f)
        except FileNotFoundError:
            print(f"Config file {config_path} not found. Using defaults.")
            self.config = {
                "subreddit": "test"
            }
    
    def post_to_reddit(self, title, content, subreddit=None):
        """Post content to a specified subreddit"""
        try:
            if subreddit is None:
                subreddit = self.config.get("subreddit", "test")
            
            # Submit the post
            submission = self.reddit.subreddit(subreddit).submit(
                title=title,
                selftext=content
            )
            
            print(f"Successfully posted: {submission.title}")
            print(f"Post URL: {submission.url}")
            
            return {
                "success": True,
                "url": submission.url,
                "id": submission.id,
                "title": submission.title
            }
        except Exception as e:
            print(f"Error posting to Reddit: {e}")
            return {
                "success": False,
                "error": str(e)
            }

if __name__ == "__main__":
    # Test the Reddit poster
    poster = RedditPoster()
    result = poster.post_to_reddit(
        "Test AI Generated Post",
        "This is a test post generated by an AI agent."
    )
    print(result)