import praw
import json
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class RedditPoster:
    def __init__(self, config_path="config.json"):
        """Initialize the Reddit poster with credentials from config file"""
        # Load credentials from environment variables
        client_id = os.getenv("REDDIT_CLIENT_ID")
        client_secret = os.getenv("REDDIT_CLIENT_SECRET")
        username = os.getenv("REDDIT_USERNAME")
        password = os.getenv("REDDIT_PASSWORD")
        user_agent = os.getenv("REDDIT_USER_AGENT", f"RedditSQA/1.0 by u/{username}")
        
        # Initialize PRAW instance
        self.reddit = praw.Reddit(
            client_id=client_id,
            client_secret=client_secret,
            username=username,
            password=password,
            user_agent=user_agent
        )
        
        # Load additional config from file if needed
        try:
            with open(config_path, 'r') as f:
                self.config = json.load(f)
        except FileNotFoundError:
            print(f"Config file {config_path} not found. Using defaults.")
            self.config = {
                "subreddit": "test"
            }
    
    def post_to_reddit(self, title, content, subreddit=None):
        """Post content to a specified subreddit"""
        try:
            if subreddit is None:
                subreddit = self.config.get("subreddit", "test")
            
            # Check if the subreddit exists and we have permission to post
            subreddit_obj = self.reddit.subreddit(subreddit)
            
            # Submit the post
            submission = subreddit_obj.submit(
                title=title,
                selftext=content
            )
            
            print(f"Successfully posted: {submission.title}")
            print(f"Posted by: {submission.author}")
            print(f"Post URL: {submission.url}")
            print(f"Subreddit: r/{submission.subreddit.display_name}")
            
            return {
                "success": True,
                "url": submission.url,
                "id": submission.id,
                "title": submission.title,
                "subreddit": submission.subreddit.display_name,
                "author": str(submission.author)
            }
        except praw.exceptions.APIException as e:
            print(f"Reddit API Error: {e}")
            return {
                "success": False,
                "error": f"Reddit API Error: {str(e)}"
            }
        except Exception as e:
            print(f"Error posting to Reddit: {e}")
            return {
                "success": False,
                "error": str(e)
            }

if __name__ == "__main__":
    # Test the Reddit poster
    poster = RedditPoster()
    result = poster.post_to_reddit(
        "Test AI Generated Post",
        "This is a test post generated by an AI agent."
    )
    print(result)